### ISSUE TITLE
The roadmap

### ISSUE THREAD

**Issue by ShevtsovPM** [ShevtsovPM/vk_friends_parser#8]
### Basic features:
- [x] Create basic parser logic [Python, MongoDB].
- [ ] Add handling for captures [Python].
- [ ] Add backgrounding for parsing [Celery + Redis]. Only one task is allowed at one time. 
- [ ] Add drawing results as a graph [pyplot].
- [ ] Add simple FastAPI server [FastAPI + Pydantic + (HTML + JS + CSS)]:
   - To start the task.
   - To stop the task.
   - To draw results (in real time would be awesome!).
- [ ] Add analysis for graph [Python]:
   - [ ] Add drawing chain from a person to other person in graph.
   - [ ] Add searching some person + drawing chain if connection exists.
- [ ] Add users and their records. One user - one draw. [FastAPI + MongoDB].
